[build-system]
requires = ["setuptools>=78.1.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tgmusicbot"
version = "1.1.8"
description = "Telegram Music Bot"
license = "AGPL-3.0"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Ashok Shau", email = "ashokshau@t.me" }
]
dependencies = [
    "aiofiles~=24.1.0",
    "APScheduler~=3.11.0",
    "cachetools~=5.5.2",
    "kurigram~=2.2.1",
    "meval~=2.5",
    "motor~=3.7.0",
    "ntgcalls~=1.3.4",
    "pillow~=11.2.1",
    "psutil~=7.0.0",
    "py-yt-search~=0.2",
    "pycryptodome~=3.22.0",
    "pydantic~=2.11.3",
    "PyTgCrypto~=1.2.9.2",
    "python-dotenv~=1.1.0",
    "pytdbot~=0.9.2",
    "pytz~=2025.2",
    "tdjson~=1.8.47",
    "ujson~=5.10.0",
    "yt-dlp~=2025.3.31",
    "py-tgcalls @ git+https://github.com/pytgcalls/pytgcalls.git@master",
]

[project.optional-dependencies]
dev = [
    "setuptools~=78.1.0",
]

[project.scripts]
tgmusicbot = "src.__main__:main"

[tool.setuptools]
packages = ["src"]
